from pathlib import Path
p=Path('src/data/biodiversity.ts');s=p.read_text(encoding='utf-8');s="import localObservations from './local-observations.json';\nimport birdRecord from './local-bird.json';\nimport radiusCounts from '../../public/bibliography/radius-counts.json';\n"+s;s=s.replace("center: null, observations: [], period: 'Periodo por definir', selectedIds: []", "center: {latitude:19.35,longitude:-99.2833333333,name:'19°21′ N · 99°17′ O'}, observations: localObservations as SpeciesObservation[], period: 'iNaturalist · grado de investigación · hasta 03 oct 2026', selectedIds: localObservations.map(o=>o.id)");s=s.replace("source?: string} = {};","source?: string} = birdRecord;\nexport const counts = radiusCounts;");p.write_text(s,encoding='utf-8')
p=Path('src/data/mediaManifest.ts');s=p.read_text(encoding='utf-8');s="import { localBird } from './biodiversity';\n"+s;start=s.index(" bird: {path:");end=s.index('\n};',start);s=s[:start]+" bird: {path:localBird.audio || null,loop:false,label:'Vocalización real · colibrí orejas blancas · ver créditos'},"+s[end:];p.write_text(s,encoding='utf-8')
p=Path('src/components/SceneView.tsx');s=p.read_text(encoding='utf-8-sig');s="import { metadata } from '../data/presentation';\nimport { biodiversity, localBird, counts } from '../data/biodiversity';\nimport { nearbyPlace, observedLayers, investigationLayers } from '../data/places';\nimport { poems } from '../data/poems';\nimport { BirdReveal, BiodiversityRadiusMap, PlaceLayers, CommunityScienceFlow, ObservationRecord } from './LocalNature';\n"+s
s=s.replace('reduced,onStart,onPlace}', 'reduced,onStart,onPlace,onReplay}').replace('onPlace:(id:string)=>void})','onPlace:(id:string)=>void;onReplay:()=>void})')
a=s.index(" if(scene.layout==='opening')");b=s.index(" if(current.kind==='black')",a)
s=s[:a]+''' if(scene.layout==='opening')return <div className="opening-content"><div className="opening-eyebrow"><span/> UNA INVITACIÓN A DETENERSE</div><h1>Entre concreto:<br/><em>una flor y un canto</em></h1><p className="opening-subtitle">{metadata.subtitle}</p><button className="start-button" onClick={onStart}>Comenzar el recorrido <span>↗</span></button></div>;
 if(scene.layout==='bird-reveal')return <BirdReveal {...localBird} step={step} onReplay={onReplay}/>;
 if(scene.layout==='radius-map')return <BiodiversityRadiusMap {...biodiversity} radii={[1,2,5]} counts={counts}/>;
 if(scene.layout==='place-layers')return <PlaceLayers step={step} observedLayers={observedLayers} investigationLayers={investigationLayers}/>;
 if(scene.layout==='community-flow')return <CommunityScienceFlow step={step}/>;
 if(scene.layout==='observation')return <ObservationRecord step={step} image={localBird.image}/>;
 if(scene.layout==='resolution'&&step===1)return <div className="resolution-species">{biodiversity.observations.slice(0,6).map(o=><article key={o.id}>{o.photo&&<img src={asset(o.photo)} alt={o.commonName} loading="lazy"/>}<h3>{o.commonName}</h3><em>{o.scientificName}</em></article>)}</div>;
 if(scene.layout==='dimensions'&&step===1)return <div className="landscape-dimensions"><section><p className="eyebrow">FÍSICO</p><h2>Lo que está ahí.</h2><p>roca · agua · vegetación<br/>relieve · animales</p></section><section><p className="eyebrow">VIVIDO</p><h2>Lo que aprendemos.</h2><p>nombres · recuerdos · mitos<br/>caminos · afectos · usos</p></section></div>;
 if(scene.layout==='nearby')return <div className="generic-scene">{nearbyPlace.image&&<img className="nearby-image" src={asset(nearbyPlace.image)} alt={nearbyPlace.name}/>}<h2>{current.text}</h2>{!nearbyPlace.image&&<p className="scene-detail">Fotografía del espacio cercano pendiente · imaginemos el lugar que queremos conocer.</p>}</div>;
 if(scene.layout==='poem'&&current.kind){const poem=poems[current.kind as 'libai'|'heine'];return <div className="generic-scene poem-pause">{import.meta.env.DEV?<><h2 className="editorial-placeholder">{poem.placeholder}</h2><p className="scene-detail">{poem.label} · no proyectar como cita</p></>:<p className="eyebrow">UNA PAUSA PARA PERMANECER</p>}</div>;}
''' +s[b:]
p.write_text(s,encoding='utf-8')
p=Path('src/App.tsx');s=p.read_text(encoding='utf-8-sig').replace("chapters, presentation", "chapters, presentation, supplementaryScenes")
s=s.replace('const audio=useAudio(current.audio);','const audio=useAudio(current.audio);')
s=s.replace("/^[1-8]$/","/^[1-7]$/").replace("['1–8'","['1–7'").replace('Ocho movimientos.','Siete actos.').replace('APRENDER A MIRAR','ENTRE CONCRETO').replace('<small>/ 30</small>','<small>/ {presentation.length}</small>').replace('index===29','index===presentation.length-1')
s=s.replace("scene.layout==='bird'||", "scene.layout==='bird-reveal'||scene.layout==='bird'||")
s=s.replace("!quiet&&<header", "!quiet&&!scene.concealed&&<header").replace("index!==0&&!quiet&&", "index!==0&&!quiet&&!scene.concealed&&")
s=s.replace("onPlace={setPlace}/>","onPlace={setPlace} onReplay={audio.replay}/>")
s=s.replace("(quiet?'quiet ':'')", "(quiet?'quiet ':'')+(scene.concealed?'concealed ':'')")
s=s.replace("<img src={imagePath(currentImage)}", "<img onError={e=>{e.currentTarget.style.visibility='hidden';}} src={imagePath(currentImage)}")
s=s.replace("const sourceList=panel==='bibliography'?sources:scene.sources.map(id=>sourceById[id]);", "const sourceList=panel==='bibliography'?sources:scene.sources.map(id=>sourceById[id]).filter(Boolean);")
s=s.replace("...(scene.layout==='bird'?['forest','bird-song']:[])","...(scene.layout==='bird-reveal'?['local-song',...mediaManifest.filter(m=>m.id.startsWith('local-')).map(m=>m.id)]:[]),...(scene.layout==='radius-map'||scene.layout==='resolution'||scene.layout==='observation'?mediaManifest.filter(m=>m.id.startsWith('local-')).map(m=>m.id):[])")
s=s.replace('el canto del petirrojo está pendiente de incorporar con su acreditación','la vocalización local incluye su registro y licencia')
s=s.replace("Object.entries(scene.notes).map", "Object.entries(scene.notes).filter(([key])=>!['say','question'].includes(key)).map")
s=s.replace("caution:'Distinción importante'", "caution:'Distinción importante',speakerNotes:'Qué decir',audiencePrompt:'Pregunta al público',evidenceType:'Tipo de evidencia',sources:'Referencias'")
s=s.replace("}[key]}</h4>","} as Record<string,string>)[key]}</h4>").replace("<h4>{{objective:","<h4>{({objective:")
s=s.replace('<h3 className="credits-title">Créditos audiovisuales</h3>', '<h3 className="credits-title">Créditos audiovisuales</h3>')
s=s.replace("{panel==='sources'&&<button", "{panel==='bibliography'&&<section className=\"supplementary\"><h3>Material complementario preservado</h3>{supplementaryScenes.map(s=><details key={s.id}><summary>{s.title}</summary><p>{s.notes.say}</p><p>{s.notes.caution}</p></details>)}</section>}{panel==='sources'&&<button")
p.write_text(s,encoding='utf-8')
p=Path('src/hooks/useAudio.ts');s=p.read_text(encoding='utf-8');s=s.replace("const [enabled,setEnabled]", "const [replayKey,setReplayKey]=useState(0);\n const [enabled,setEnabled]");s=s.replace("if(old)fade(old,0,true);","if(old){const pending=fades.current.get(old);if(pending)cancelAnimationFrame(pending);old.pause();players.current.delete(old);}");s=s.replace('fade(el,0,true);};','const pending=fades.current.get(el);if(pending)cancelAnimationFrame(pending);el.pause();players.current.delete(el);};');s=s.replace('[id,enabled,fade]','[id,enabled,fade,replayKey]');s=s.replace('return {enabled,toggle:', 'return {enabled,replay:()=>{setEnabled(true);setReplayKey(k=>k+1);},toggle:');p.write_text(s,encoding='utf-8')
p=Path('src/data/themes.ts');s=p.read_text(encoding='utf-8').replace("contemplative:{bg:'#172923',ink:'#f1f0df',accent:'#d6d9b0'}", "contemplative:{bg:'#202e3b',ink:'#f0f0e9',accent:'#b8cbbd'}");p.write_text(s,encoding='utf-8')
p=Path('index.html');s=p.read_text(encoding='utf-8-sig');import re;s=re.sub(r'<title>.*?</title>','<title>Entre concreto: una flor y un canto</title>',s);s=re.sub(r'(<meta name="description" content=")[^"]*',r'\1Naturaleza, asombro y el derecho a disfrutar del mundo. Una mirada al vínculo entre naturaleza y bienestar humano, desde la biofilia y el asombro hasta la belleza, la biodiversidad y el paisaje; una invitación a detenernos, observar nuestro entorno y redescubrir el goce de estar entre lo vivo.',s);p.write_text(s,encoding='utf-8')
