import { useCallback, useEffect, useState } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowLeft, ArrowRight, AudioLines, BookOpen, Check, ChevronRight, Expand, Eye, EyeOff, Keyboard, List, Mountain, Pause, Settings2, Volume2, VolumeX, X } from 'lucide-react';
import { chapters, presentation, supplementaryScenes } from './data/presentation';
import { sourceById, sources } from './data/sources';
import { imagePath, mediaById, mediaManifest } from './data/mediaManifest';
import { themes } from './data/themes';
import { backward, forward, parseHash } from './hooks/navigation.mjs';
import { useAudio } from './hooks/useAudio';
import SceneView, { PlaceCard } from './components/SceneView';
import Drawer from './components/Drawer';
type Panel = 'index'|'sources'|'notes'|'help'|'settings'|'bibliography'|null;
export default function App(){
 const [position,setPosition]=useState<number[]>(()=>parseHash(location.hash,presentation));
 const [panel,setPanel]=useState<Panel>(null);const [place,setPlace]=useState<string|null>(null);
 const [showProgress,setShowProgress]=useState(true);const [quiet,setQuiet]=useState(true);const [manualReduced,setManualReduced]=useState(false);
 const [elapsed,setElapsed]=useState(0);const [clockRunning,setClockRunning]=useState(false);const [offline,setOffline]=useState('');const [fullscreenError,setFullscreenError]=useState('');
 const prefersReduced=useReducedMotion();const reduced=!!prefersReduced||manualReduced;
 const [index,step]=position;const scene=presentation[index];const current=scene.steps[step];const theme=themes[scene.theme];
 const audio=useAudio(current.audio);const currentImage=current.image||scene.image;
 const go=useCallback((i:number,s=0)=>{setPosition([i,s]);setPanel(null);setPlace(null);if(i>0)setClockRunning(true);},[]);
 const next=useCallback(()=>{setPosition(p=>forward(p,presentation));setClockRunning(true);},[]);
 const prev=useCallback(()=>setPosition(p=>backward(p,presentation)),[]);
 const fullscreen=useCallback(()=>{setFullscreenError('');if(!document.fullscreenElement)setQuiet(true);const action=document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();action?.catch(()=>setFullscreenError('No se pudo activar la pantalla completa. Abre la presentación en una ventana del navegador.'));},[]);
 useEffect(()=>{const hash='#'+scene.id+(step?'/'+step:'');history.replaceState(null,'',hash);},[scene.id,step]);
 useEffect(()=>{const fn=()=>setPosition(parseHash(location.hash,presentation));window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn);},[]);
 useEffect(()=>{if(!clockRunning)return;const t=setInterval(()=>setElapsed(n=>n+1),1000);return()=>clearInterval(t);},[clockRunning]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{
  if(e.key==='Escape'){setPanel(null);setPlace(null);return;}
  if(e.key.toLowerCase()==='p'&&panel==='notes'){setPanel(null);return;}
  if(panel||place)return;
  if(e.target instanceof HTMLElement&&(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable))return;
  if((e.key===' '||e.key==='Enter')&&e.target instanceof HTMLElement&&e.target.closest('button,a'))return;
  const key=e.key.toLowerCase();if(['arrowright','arrowleft','arrowdown','arrowup',' ','home','end'].includes(key))e.preventDefault();
  if(key==='arrowright'||key===' ')next();else if(key==='arrowleft')prev();else if(key==='arrowdown')setPosition(p=>[p[0],Math.min(p[1]+1,presentation[p[0]].steps.length-1)]);else if(key==='arrowup')setPosition(p=>[p[0],Math.max(0,p[1]-1)]);
  else if(key==='home')go(0);else if(key==='end')go(presentation.length-1);else if(key==='f')fullscreen();else if(key==='m')audio.toggle();else if(key==='p')setPanel('notes');else if(key==='s')setPanel('settings');else if(key==='r')setPanel('sources');else if(key==='i')setPanel('index');else if(key==='h')setQuiet(q=>!q);else if(key==='?')setPanel('help');else if(/^[1-7]$/.test(key))go(chapters[Number(key)-1].start);
 };window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[next,prev,go,fullscreen,audio.toggle,panel,place]);
 useEffect(()=>{const nextScene=presentation[index+1];const id=nextScene?.steps[0].image||nextScene?.image;if(id){const img=new Image();img.src=imagePath(id)||'';}},[index]);
 useEffect(()=>{const handle=(e:MessageEvent)=>{if(e.data.type==='OFFLINE_READY')setOffline('Lista para usar sin conexión');if(e.data.type==='OFFLINE_ERROR')setOffline('No se completó la descarga. Reintenta con conexión.');};navigator.serviceWorker?.addEventListener('message',handle);return()=>navigator.serviceWorker?.removeEventListener('message',handle);},[]);
 const prepareOffline=async()=>{if(!('serviceWorker' in navigator)||!import.meta.env.PROD){setOffline('Usa la versión compilada (npm run preview) para preparar la copia sin conexión.');return;}setOffline('Descargando todos los recursos…');try{const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'CACHE_ALL'});}catch{setOffline('No se pudo preparar la copia. La carpeta dist también funciona con un servidor local.');}};
 const elapsedText=String(Math.floor(elapsed/60)).padStart(2,'0')+':'+String(elapsed%60).padStart(2,'0');
 const backgroundHidden=current.kind==='black'||scene.theme==='black'||scene.layout==='bird-reveal'||scene.layout==='bird'||(scene.layout==='social'&&step===0)||scene.layout==='map'||scene.layout==='experiment';
 const sourceList=panel==='bibliography'?sources:scene.sources.map(id=>sourceById[id]).filter(Boolean);
 return <main onDoubleClick={e=>{if(!(e.target as HTMLElement).closest('button,a,input,dialog'))setQuiet(q=>!q);}} className={'presentation '+(quiet?'quiet ':'')+(scene.concealed?'concealed ':'')+(reduced?'reduced ':'')+(scene.theme==='paper'?'paper ':'')+(index===0?'is-opening ':'')+'theme-'+scene.theme} style={{'--bg':theme.bg,'--ink':theme.ink,'--accent':theme.accent} as React.CSSProperties}>
  <AnimatePresence initial={false}>{!backgroundHidden&&currentImage&&<motion.div className={'scene-background '+(current.kind||'')} key={currentImage} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduced?0:1.2}}><img onError={e=>{e.currentTarget.style.visibility='hidden';}} src={imagePath(currentImage)} alt={mediaById[currentImage]?.alt || 'Fotografía pendiente de incorporar'}/></motion.div>}</AnimatePresence><div className="scene-shade"/>
  {!quiet&&!scene.concealed&&<header className="topbar"><button className="brand" onClick={()=>go(0)} aria-label="Volver al preludio"><Mountain size={26} strokeWidth={1}/><span>ENTRE CONCRETO</span></button><div className="top-center">PAISAJE <i/> NATURALEZA <i/> PERCEPCIÓN</div><button className="index-button" onClick={()=>setPanel('index')}><span>El recorrido</span><List size={18}/></button></header>}
  <div className="stage" aria-live="polite" aria-atomic="false" data-scene={scene.id} data-step={step}>
   {index!==0&&!quiet&&!scene.concealed&&<div className="scene-label"><span>{String(index).padStart(2,'0')}</span><i/>{scene.title}</div>}
   <AnimatePresence mode="wait" initial={false}><motion.div className="scene-content" key={scene.id} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduced?0:scene.theme==='paper'?.1:.45}}><SceneView key={scene.id} scene={scene} step={step} reduced={reduced} onStart={next} onPlace={setPlace} onReplay={audio.replay}/></motion.div></AnimatePresence>
  </div>
  {!quiet&&<footer className="controls"><div className="controls-line"><div className="sound-controls"><button className={'sound-button '+(audio.enabled?'enabled':'')} onClick={audio.toggle} title={audio.label} aria-label={audio.enabled?'Silenciar sonido (M)':'Activar sonido (M)'}>{audio.enabled?<AudioLines size={18}/>:<VolumeX size={18}/>}<span>{audio.enabled?'Sonido activado':'Activar sonido'}</span></button><span className="control-divider"/><button className="source-button" onClick={()=>setPanel('sources')}>↗ fuente</button></div><div className="scene-progress"><span>{index===0?'PRELUDIO':chapters[scene.chapter].name.toUpperCase()}</span><i/>{String(index+1).padStart(2,'0')} <small>/ {presentation.length}</small>{scene.steps.length>1&&<div className="step-dots" aria-label={'Paso '+(step+1)+' de '+scene.steps.length}>{scene.steps.map((_,s)=><button key={s} onClick={()=>setPosition([index,s])} className={s===step?'active':''} aria-label={'Ir al paso '+(s+1)} aria-current={s===step?'step':undefined}/>)}</div>}</div><div className="control-actions"><button onClick={()=>setPanel('help')} title="Atajos de teclado (?)" aria-label="Ayuda y atajos"><Keyboard size={17}/></button><button onClick={()=>setPanel('settings')} title="Preferencias" aria-label="Abrir preferencias"><Settings2 size={17}/></button><button onClick={fullscreen} title="Pantalla completa (F)" aria-label="Pantalla completa"><Expand size={17}/></button><span className="control-divider"/><button onClick={prev} disabled={index===0&&step===0} aria-label="Anterior"><ArrowLeft size={21}/></button><button className="next-button" onClick={next} disabled={index===presentation.length-1&&step===scene.steps.length-1} aria-label="Siguiente"><ArrowRight size={21}/></button></div></div>
   {showProgress&&<nav className="chapter-progress" aria-label="Capítulos">{chapters.map((c,i)=><button key={c.name} onClick={()=>go(c.start)} className={scene.chapter===i?'active':scene.chapter>i?'passed':''} aria-current={scene.chapter===i?'step':undefined}><span>{String(i+1).padStart(2,'0')}</span>{c.name}<i/></button>)}</nav>}
  </footer>}

  {(audio.error||fullscreenError)&&<div className="toast" role="status">{audio.error||fullscreenError}</div>}
  {panel&&<Drawer title={{index:'El recorrido',sources:'Fuentes de esta escena',notes:'Notas del expositor',help:'A tu ritmo',settings:'Preparar la experiencia',bibliography:'Referencias y lecturas'}[panel]} wide={panel==='index'||panel==='bibliography'} onClose={()=>setPanel(null)}>
   {panel==='index'&&<><p className="drawer-intro">Siete actos. Una manera distinta de mirar.<br/>Elige un lugar del recorrido para continuar.</p><div className="chapter-index">{chapters.map((c,i)=><section key={c.name}><h3><span>{String(i+1).padStart(2,'0')}</span>{c.name}<small>{c.subtitle}</small></h3>{presentation.map((s,j)=>s.chapter===i?<button key={s.id} className={j===index?'current':''} onClick={()=>go(j)}><span>{String(j).padStart(2,'0')}</span>{s.title}<ChevronRight size={14}/></button>:null)}</section>)}</div><button className="text-link" onClick={()=>setPanel('bibliography')}>Referencias y lecturas ↗</button></>}
   {(panel==='sources'||panel==='bibliography')&&<><p className="drawer-intro">Evidencia, interpretación y poesía tienen lugares distintos en este recorrido.</p>{sourceList.map(s=><article className="source-entry" key={s.id}><span className="source-type">{s.type}</span><h3>{s.title}</h3><p className="source-meta">{s.author} · {s.year}</p>{s.chapter&&<p>{s.chapter}</p>}<p>{s.idea}</p>{s.status&&<p className="source-status">{s.status}</p>}{s.url&&<a href={s.url} target="_blank" rel="noreferrer">Consultar referencia ↗</a>}</article>)}<h3 className="credits-title">Créditos audiovisuales</h3>{(panel==='bibliography'?mediaManifest:mediaManifest.filter(m=>[currentImage,...(scene.layout==='experiment'?['office','park','forest']:[]),...(scene.layout==='map'?['wirikuta','niyamgiri','takayna','kahoolawe']:[]),...(scene.layout==='bird-reveal'?['local-song',...mediaManifest.filter(m=>m.id.startsWith('local-')).map(m=>m.id)]:[]),...(scene.layout==='radius-map'?['uam-map-1','uam-map-2','uam-map-5']:[]),...(scene.layout==='radius-map'||scene.layout==='resolution'||scene.layout==='observation'?mediaManifest.filter(m=>m.id.startsWith('local-')).map(m=>m.id):[])].includes(m.id))).map(m=><article className="media-credit" key={m.id}><strong>{m.id}</strong><p>{m.author} · {m.license}</p><p>{m.attribution}</p><a href={m.source} target="_blank" rel="noreferrer">Archivo original y licencia ↗</a></article>)}<p className="credit">Imágenes redimensionadas y convertidas a WebP; recortes de encuadre en pantalla. Las obras CC BY-SA conservan su licencia. Ambientes de demostración sintetizados localmente; la vocalización local incluye su registro y licencia. El video de escala anterior se conserva en el archivo, fuera del recorrido principal.</p>{panel==='bibliography'&&<section className="supplementary"><h3>Material complementario preservado</h3>{supplementaryScenes.map(s=><details key={s.id}><summary>{s.title}</summary><p>{s.notes.say}</p><p>{s.notes.caution}</p></details>)}</section>}{panel==='sources'&&<button className="text-link" onClick={()=>setPanel('bibliography')}>Ver toda la bibliografía ↗</button>}</>}
   {panel==='notes'&&<><div className="rehearsal"><span>{elapsedText}<small>tiempo transcurrido</small></span><button onClick={()=>setClockRunning(v=>!v)}>{clockRunning?'Pausar reloj':'Reanudar reloj'}</button><button onClick={()=>{setElapsed(0);setClockRunning(false);}}>Reiniciar</button></div><p className="notes-warning">Este panel es visible en esta pantalla. Ciérralo antes de proyectar.</p><p className="eyebrow">ESCENA {index} · {scene.minutes||'∞'} MIN · PASO {step+1}/{scene.steps.length}</p><h3>{scene.title}</h3>{Object.entries(scene.notes).filter(([key])=>!['say','question'].includes(key)).map(([key,value])=><section className={'note note-'+key} key={key}><h4>{({objective:'Objetivo',idea:'Idea central',say:'Qué decir',question:'Pregunta',pause:'Pausa',caution:'Distinción importante',speakerNotes:'Qué decir',audiencePrompt:'Pregunta al público',evidenceType:'Tipo de evidencia',sources:'Referencias'} as Record<string,string>)[key]}</h4><p>{value}</p></section>)}<p className="next-scene">Después: {presentation[index+1]?.title||'Mantener el silencio.'}</p><button className="text-link" onClick={()=>setPanel('sources')}>Fuentes de la escena ↗</button></>}
   {panel==='help'&&<><p className="drawer-intro">Tú decides cuándo seguir. Cada avance revela una capa antes de cambiar de escena.</p><div className="shortcut-list">{[['→ / Espacio','Avanzar paso o escena'],['←','Regresar paso o escena'],['↓ / ↑','Recorrer pasos internos'],['Inicio / Fin','Primera / última escena'],['1–7','Saltar de capítulo'],['F','Pantalla completa'],['M','Activar / silenciar sonido'],['P','Notas del expositor'],['I','Índice del recorrido'],['H / doble clic','Ocultar / mostrar controles'],['S','Preferencias'],['R','Fuentes de la escena'],['Esc','Cerrar panel o salir de pantalla completa']].map(([key,label])=><div key={key}><kbd>{key}</kbd><span>{label}</span></div>)}</div></>}
   {panel==='settings'&&<><p className="drawer-intro">Luz baja. Sonido suave. Tiempo para detenerse.</p><section className="setting"><h3>Sonido ambiental</h3><button onClick={audio.toggle}>{audio.enabled?<Volume2 size={18}/>:<VolumeX size={18}/>} {audio.enabled?'Silenciar':'Activar sonido'}</button><label>Volumen <span>{Math.round(audio.volume*100)} %</span><input type="range" min="0" max="1" step=".01" value={audio.volume} onChange={e=>audio.setVolume(Number(e.target.value))}/></label><p className="credit">{audio.label}</p></section><section className="setting"><label className="check-row"><input type="checkbox" checked={manualReduced||!!prefersReduced} disabled={!!prefersReduced} onChange={e=>setManualReduced(e.target.checked)}/> Reducir movimiento</label><label className="check-row"><input type="checkbox" checked={showProgress} onChange={e=>setShowProgress(e.target.checked)}/> Mostrar el recorrido inferior</label><button onClick={()=>{setQuiet(true);setPanel(null);}}><EyeOff size={17}/> Ocultar controles · H</button></section><section className="setting"><h3>Disponible sin conexión</h3><p>Guarda la presentación completa en este navegador antes de desconectarte.</p><button onClick={prepareOffline}>Preparar copia sin conexión ↓</button>{offline&&<p className="offline-status" role="status">{offline}</p>}</section><button className="text-link" onClick={()=>setPanel('notes')}>Abrir notas y reloj de ensayo ↗</button></>}
  </Drawer>}
  {place&&<Drawer title="Un lugar, una relación" onClose={()=>setPlace(null)}><PlaceCard id={place}/></Drawer>}
 </main>;
}
